export const ALL_EMPLOYEES: string[] = [
  "Suvajit Pal",
  "Lakshit L Shah",
  "Jyoti Gorwani",
  "Karan Manohar Vichare",
  "Vaishnavi B",
  "Nandha Kumar Murugesan",
  "Ratnadip Suresh Bhorge",
  "Geeta A",
  "Jyothi Shashi Kumar",
  "Satwik K A",
  "Ronak Rupin Choksy",
  "Maddila Sri Nandini",
  "Varun Pundhir",
  "Subham Singha",
  "Raman Rawat",
  "Charanya Balasubramanian",
  "Vishal Yadav",
  "Sanket Manoj Sagvekar",
  "Kotadiya Mehul",
  "Soubhagya Dubey",
  "Avinash Kumar",
  "S Keerthivasan",
  "Giridhar Ravikumar",
  "Vivek Chandra Joshi",
  "Rajesh Shubham Patel",
  "M Chakravarthiraj",
  "Kavya AR",
  "Ajay Singh Chouhan",
  "B Janani",
  "Mohammad Saddam Hussain",
  "Rajan Jitendra Singh",
  "Nitish Nagesh Shet",
  "T S Gowtham",
  "Deepshika DJ",
  "Mamta .",
  "Shrikant Shankar Pawar",
  "Devanshu Nahak",
  "Manudev Kumar",
  "Shikha Saxena",
  "Prerana Vidyadhar Chavan",
  "Apoorv Kumar Pharswal",
  "S Nasarul Haq Al Hassan",
  "Mandala Vijaykanth",
  "Rithanya R B",
  "Surya G M",
  "Pavithra Hari",
  "Ajinkya Kishor Kini",
  "Aakash Arasu",
  "Pihu Nayak",
  "Harsha Gupta",
  "Aditya Krishnan",
  "Marella Raghava Reddy",
  "Sivaganapathy S",
  "Trupti Hemant Dhone",
  "Sameer Sanjay Bhosale",
  "Aman Hareshkumar Jain",
  "Neha Rajendra Jogi",
  "Gunaharini J",
  "P Logesh",
  "Rohit Arun Shah",
  "Suhas Namdeo Pawar",
  "Ashutosh Kumar Singh",
  "Shubham Shrivastav",
  "Sonu Kejriwal",
  "Mohit Pal",
  "Aaditya S",
  "Athika A",
  "Siddharth P Reddy",
  "Pravin Moses Gladvin",
  "Charless Binny Kumaravel",
  "Tina Kashyap",
  "Shashank Reddy Mopuru",
  "Padmasree T",
  "Shaik Sameer Babu",
  "Asish Venkata Korukonda Jaya Chand Sri Korukonda",
  "Jones Augustine G",
  "S Sivassri",
  "Omkar Vaijanath More",
];
